const pickUserResponse = (user) => ({
  id: user.id,
  name: user.name,
  email: user.email,
  role: user.role,
  approvalStatus: user.approvalStatus,
  ngoOrganizationName: user.ngoOrganizationName,
  ngoRegistrationNumber: user.ngoRegistrationNumber,
  ngoContactPhone: user.ngoContactPhone,
  ngoAddress: user.ngoAddress,
  ngoDescription: user.ngoDescription,
  ngoSsmDocumentUrl: user.ngoSsmDocumentUrl,
  ngoSsmDocumentPublicId: user.ngoSsmDocumentPublicId,
  ngoSupportingDocUrls: user.ngoSupportingDocUrls,
  ngoSupportingDocPublicIds: user.ngoSupportingDocPublicIds,
  vendorBusinessName: user.vendorBusinessName,
  vendorRegistrationNumber: user.vendorRegistrationNumber,
  vendorPlaceAddress: user.vendorPlaceAddress,
  vendorContactPhone: user.vendorContactPhone,
  vendorDescription: user.vendorDescription,
  vendorSsmDocumentUrl: user.vendorSsmDocumentUrl,
  vendorSsmDocumentPublicId: user.vendorSsmDocumentPublicId,
  riderLicenseNumber: user.riderLicenseNumber,
  riderPhoneNumber: user.riderPhoneNumber,
  riderVehicleType: user.riderVehicleType,
  riderVehicleName: user.riderVehicleName,
  riderVehiclePlateNumber: user.riderVehiclePlateNumber,
  riderVehicleColor: user.riderVehicleColor,
  riderAddress: user.riderAddress,
  riderNotes: user.riderNotes,
  riderLicenseDocumentUrl: user.riderLicenseDocumentUrl,
  riderLicenseDocumentPublicId: user.riderLicenseDocumentPublicId,
  riderVehicleGrantUrl: user.riderVehicleGrantUrl,
  riderVehicleGrantPublicId: user.riderVehicleGrantPublicId,
  approvalNotes: user.approvalNotes,
  approvedAt: user.approvedAt,
  createdAt: user.createdAt,
  updatedAt: user.updatedAt
});

module.exports = pickUserResponse;
